version: '2'

services:
  mailman-core:
    image: mailman-core:latest
    hostname: mailman-core
    volumes:
      - ./mailman/mailman-extra.cfg:/opt/mailman/mailman-extra.cfg
      - ./db:/opt/mailmandb
    stop_grace_period: 30s
    environment:
      - DATABASE_TYPE=sqlite
      - DATABASE_URL=sqlite:////opt/mailmandb/mailmanweb.db
      - DATABASE_CLASS=mailman.database.sqlite.SQLiteDatabase
      - HYPERKITTY_API_KEY=test
      - HYPERKITTY_URL=http://mailman-web:8000/mailman3/hyperkitty/
      - INIT_DEV=1
    ports:
      - "8001:8001" # API
      - "8024:8024" # LMTP - incoming emails
    networks:
      mailman:

  mailman-web:
    image: mailman-web:latest
    hostname: mailman-web
    depends_on:
      - mailman-core
    links:
      - mailman-core:mailman-core
    volumes:
      - ./mailman/web:/opt/mailman-web-data
      - ./messages:/tmp/mailman-messages
      - ./db:/opt/mailmandb
    environment:
      - DATABASE_TYPE=sqlite
      - DATABASE_URL=sqlite:////opt/mailmandb/mailmanweb.db
      - DATABASE_CLASS=mailman.database.sqlite.SQLiteDatabase
      - HYPERKITTY_API_KEY=test
      - SECRET_KEY=test
      - MAILMAN_ADMIN_USER=admin
      - MAILMAN_ADMIN_EMAIL=admin@example.com
      - SERVE_FROM_DOMAIN=localhost
      - URL_BASE_DIR=mailman3
    networks:
      mailman:

  caddy:
    image: caddy:2.3.0-alpine
    restart: unless-stopped
    depends_on: 
      - mailman-web
    ports:
      - "8000:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./mailman/web/static:/var/www/mailman3/static
      - caddy_data:/data
      - caddy_config:/config
    networks:
      mailman:

volumes: 
  caddy_data:
  caddy_config:

networks:
   mailman: